# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GO-st' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GO-st

  pod 'SwiftKeychainWrapper'
  pod 'Alamofire'
  pod 'Then'
  pod 'SnapKit'
  pod 'R.swift'
  pod 'lottie-ios'
end
